/** The kit's English: every kit area's messages in one flat catalogue. Bundled; the fallback for every key. Generated by scripts/locales-index.ts. */
import agenda from './en/agenda.js';
import appBar from './en/appBar.js';
import calendar from './en/calendar.js';
import calendarExport from './en/calendarExport.js';
import chart from './en/chart.js';
import common from './en/common.js';
import condition from './en/condition.js';
import contacts from './en/contacts.js';
import dose from './en/dose.js';
import feedback from './en/feedback.js';
import food from './en/food.js';
import gmail from './en/gmail.js';
import googleTasks from './en/googleTasks.js';
import googleToken from './en/googleToken.js';
import home from './en/home.js';
import hours from './en/hours.js';
import household from './en/household.js';
import image from './en/image.js';
import invite from './en/invite.js';
import people from './en/people.js';
import photo from './en/photo.js';
import places from './en/places.js';
import push from './en/push.js';
import reminders from './en/reminders.js';
import roles from './en/roles.js';
import schedule from './en/schedule.js';
import suggestions from './en/suggestions.js';
import time from './en/time.js';
import todos from './en/todos.js';
import ui from './en/ui.js';
import visit from './en/visit.js';

export default {
  ...agenda,
  ...appBar,
  ...calendar,
  ...calendarExport,
  ...chart,
  ...common,
  ...condition,
  ...contacts,
  ...dose,
  ...feedback,
  ...food,
  ...gmail,
  ...googleTasks,
  ...googleToken,
  ...home,
  ...hours,
  ...household,
  ...image,
  ...invite,
  ...people,
  ...photo,
  ...places,
  ...push,
  ...reminders,
  ...roles,
  ...schedule,
  ...suggestions,
  ...time,
  ...todos,
  ...ui,
  ...visit,
} as const;
