#!/usr/bin/env bun
// Usage: bun scripts/locales-index.ts   Writes src/locales/{en,es,nl}.ts from the area files in
// src/locales/en/ (one per kit area). Run after adding an area; a test fails when they're stale.
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = join(import.meta.dir, '..', 'src', 'locales');
const areas = readdirSync(join(dir, 'en'))
  .filter((f) => f.endsWith('.ts'))
  .map((f) => f.slice(0, -3))
  .sort();

export function indexSource(lang: string, list: string[]): string {
  const name = { en: 'English', es: 'Spanish', nl: 'Dutch' }[lang] ?? lang;
  const head =
    lang === 'en'
      ? `/** The kit's English: every kit area's messages in one flat catalogue. Bundled; the fallback for every key. Generated by scripts/locales-index.ts. */\n`
      : `/** The kit's ${name}, loaded when chosen (its own chunk). Typed against the English, so a missing key fails the build. Generated by scripts/locales-index.ts. */\nimport type { CatalogueOf } from '../i18n.js';\nimport type en from './en.js';\n`;
  const imports = list.map((a) => `import ${a} from './${lang}/${a}.js';`).join('\n');
  const spread = list.map((a) => `  ...${a},`).join('\n');
  const tail = lang === 'en' ? '} as const;' : '} satisfies CatalogueOf<typeof en>;';
  return `${head}${imports}\n\nexport default {\n${spread}\n${tail}\n`;
}

if (import.meta.main) {
  for (const lang of ['en', 'es', 'nl']) writeFileSync(join(dir, `${lang}.ts`), indexSource(lang, areas));
  console.log(`locales: ${areas.length} areas (${areas.join(', ')})`);
}
